---

- name: demo the template
  hosts: localhost
  gather_facts: false
  vars:
    data_dirs: [5, 6 7]

  tasks:
    - name: pause with render
      pause:
        prompt: "{{ lookup('template', 'demo-for.j2') }}"
