---

- name: demo the template
  hosts: localhost
  gather_facts: false
  vars:
    data_dirs: ['/marco', '/hung', '/910']

  tasks:
    - name: pause with render
      pause:
        prompt: "{{ lookup('template', 'demo-marco.j2') }}"
